name: CI Build and Format Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        dotnet-quality: 'preview'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format
      
    - name: Verify code format
      run: dotnet format --verify-no-changes
      
    - name: Build status
      if: success()
      run: echo "✅ Build and format verification passed!"