services:
  - type: web
    name: cmdshiftlearn-api
    env: docker
    dockerfilePath: ./CmdShiftLearn.Api/Dockerfile
    dockerContext: ./CmdShiftLearn.Api
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Supabase__Url
        sync: false
      - key: Supabase__ApiKey
        sync: false
      - key: Supabase__JwtSecret
        sync: false
      - key: GitHub__AccessToken
        sync: false
      - key: GitHub__Owner
        value: "deactv8"
      - key: GitHub__Repo
        value: "content"
      - key: GitHub__Branch
        value: "master"
      - key: GitHub__TutorialsPath
        value: "tutorials"
      - key: GitHub__ChallengesPath
        value: "challenges"
      - key: ContentSources__Tutorials__Source
        value: "GitHub"
      - key: ContentSources__Challenges__Source
        value: "GitHub"
      - key: OpenAI__ApiKey
        sync: false
      - key: AllowedOrigins
        value: "*"
      - key: Logging__LogLevel__Default
        value: "Debug"
      - key: Logging__LogLevel__CmdShiftLearn.Api.Services
        value: "Debug"
      - key: Logging__LogLevel__CmdShiftLearn.Api.Helpers
        value: "Debug"
    autoDeploy: true